from contextlib import AbstractContextManager
from typing import Protocol

from app.contexts.production.event_mode_kernel.service import DurableEventModeKernel
from app.shared.ids import EntityId
from app.shared.time import Clock

from .contracts import (
    InputSnapshot,
    Reference,
    SessionSuggestion,
    SuggestionDecision,
    SuggestionRun,
    SuggestionStatus,
)


class SuggestionTransaction(Protocol):
    kernel: DurableEventModeKernel

    def scope(self, event_id: EntityId, stage_id: EntityId) -> None: ...
    def lock_event(self, event_id: EntityId) -> None: ...
    def decision_scope(self, event_id: EntityId, stage_id: EntityId) -> None: ...
    def snapshot(self, event_id: EntityId, stage_id: EntityId,
                 start_cues: Reference | None, end_cues: Reference | None) -> InputSnapshot: ...
    def find_run(self, digest: str) -> SuggestionRun | None: ...
    def save_run(self, run: SuggestionRun, suggestions: tuple[SessionSuggestion, ...]) -> None: ...
    def get(self, event_id: EntityId, suggestion_id: EntityId) -> SessionSuggestion: ...
    def status(self, suggestion: SessionSuggestion) -> SuggestionStatus: ...
    def replay(self, command_id: EntityId, digest: str) -> SuggestionDecision | None: ...
    def save_decision(self, decision: SuggestionDecision) -> None: ...
    def page(self, event_id: EntityId, stage_id: EntityId, status: SuggestionStatus,
             after: EntityId | None, limit: int) -> tuple[SessionSuggestion, ...]: ...


class SuggestionRepository(Protocol):
    def transaction(self, clock: Clock) -> AbstractContextManager[SuggestionTransaction]: ...
