from contextlib import AbstractContextManager
from typing import Protocol

from app.contexts.editorial.derivation_contracts import EditorialPhraseList
from app.contexts.production.event_mode_kernel.service import DurableEventModeKernel
from app.shared.ids import EntityId
from app.shared.time import Clock

from .contracts import (
    InputSnapshot,
    Reference,
    ScheduleOffsetSetting,
    SessionSuggestion,
    SuggestionDecision,
    SuggestionRun,
    SuggestionStatus,
)
from .cue_composition import BoundaryCueComposition


class SuggestionTransaction(Protocol):
    kernel: DurableEventModeKernel

    def cue_event_scope(self, event_id: EntityId) -> None: ...
    def current_composition(self, event_id: EntityId) -> BoundaryCueComposition | None: ...
    def replay_composition(self, command_id: EntityId, digest: str
                           ) -> BoundaryCueComposition | None: ...
    def publish_cue_list(self, value: EditorialPhraseList) -> EditorialPhraseList: ...
    def save_composition(self, value: BoundaryCueComposition) -> None: ...
    def composition_history(self, event_id: EntityId, after: int, limit: int
                            ) -> tuple[BoundaryCueComposition, ...]: ...
    def scope(self, event_id: EntityId, stage_id: EntityId) -> None: ...
    def lock_event(self, event_id: EntityId) -> None: ...
    def current_offset(self, event_id: EntityId, stage_id: EntityId
                       ) -> ScheduleOffsetSetting | None: ...
    def replay_offset(self, command_id: EntityId, digest: str) -> ScheduleOffsetSetting | None: ...
    def save_offset(self, setting: ScheduleOffsetSetting) -> None: ...
    def offset_history(self, event_id: EntityId, stage_id: EntityId, after: int,
                       limit: int) -> tuple[ScheduleOffsetSetting, ...]: ...
    def decision_scope(self, event_id: EntityId, stage_id: EntityId) -> None: ...
    def snapshot(self, event_id: EntityId, stage_id: EntityId,
                 start_cues: Reference | None, end_cues: Reference | None) -> InputSnapshot: ...
    def find_run(self, digest: str) -> SuggestionRun | None: ...
    def save_run(self, run: SuggestionRun, suggestions: tuple[SessionSuggestion, ...]) -> None: ...
    def get(self, event_id: EntityId, suggestion_id: EntityId) -> SessionSuggestion: ...
    def status(self, suggestion: SessionSuggestion) -> SuggestionStatus: ...
    def replay(self, command_id: EntityId, digest: str) -> SuggestionDecision | None: ...
    def save_decision(self, decision: SuggestionDecision) -> None: ...
    def page(self, event_id: EntityId, stage_id: EntityId, status: SuggestionStatus,
             after: EntityId | None, limit: int) -> tuple[SessionSuggestion, ...]: ...


class SuggestionRepository(Protocol):
    def transaction(self, clock: Clock) -> AbstractContextManager[SuggestionTransaction]: ...
